import cn from 'classnames'
import type { Metadata } from 'next'
import { Noto_Sans_KR } from 'next/font/google'
import React from 'react'
import { Footer, Header, Sidebar } from '../components'
import '../globals.css'
import styles from './page.module.css'

const getNotoSansKR = Noto_Sans_KR({
  variable: '--fonts-noto-sans-kr',
  subsets: ['latin', 'cyrillic'],
  weight: ['300', '400', '500', '700'],
  style: ['normal'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>): React.DetailedHTMLProps<React.HtmlHTMLAttributes<HTMLHtmlElement>, HTMLHtmlElement> {
  return (
    <html lang='en'>
      <body className={cn(getNotoSansKR.className, styles.wrapper)}>
        <Header className={styles.header} />
        <Sidebar className={styles.sidebar} />
        <div className={styles.content}>{children}</div>
        <Footer className={styles.footer} />
      </body>
    </html>
  )
}
